name: Detailed Feature Proposal
description: Report a specific problem that needs solving in Alchemi Code
labels: ["proposal", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for submitting a feature request for Alchemi Code!**
        
        This template helps you describe problems that need solving. Focus on the problem - the Roo team will work to design solutions unless you want to contribute the implementation yourself.
        
        **Quality over speed:** We prefer detailed, clear problem descriptions over quick ones. Vague requests often get closed or require multiple rounds of clarification, which wastes everyone's time.
        
        **Before submitting:**
        - Search existing [Issues](https://github.com/RooCodeInc/Roo-Code/issues) and [Discussions](https://github.com/RooCodeInc/Roo-Code/discussions) to avoid duplicates
        - For general ideas, use [GitHub Discussions](https://github.com/RooCodeInc/Roo-Code/discussions/categories/feature-requests) instead of this template.

  - type: markdown
    attributes:
      label: Problem (one or two sentences)
      description: What problem are users facing?
      placeholder: e.g., "Users often click Copy Run by mistake and duplicate runs unintentionally."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context (who is affected and when)
      description: Who encounters this and in what situation?
      placeholder: e.g., "Happens when browsing the Runs list; most visible for new users."
    validations:
      required: true

  - type: textarea
    id: desired
    attributes:
      label: Desired behavior (conceptual, not technical)
      description: Describe what should happen in simple terms.
      placeholder: e.g., "Ask for confirmation before copying a run."
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: Alchemi Code Task Links (Optional)
      description: |
        If you used Alchemi Code to explore this feature request or develop solutions, share the public task links here.
        This helps maintainers understand the context and any exploration you've done.
        Example: https://app.roocode.com/share/task-id
      placeholder: Paste your Alchemi Code share links here, one per line

  - type: checkboxes
    id: checklist
    attributes:
      label: Request checklist
      options:
        - label: I've searched existing Issues and Discussions for duplicates
          required: true
        - label: This describes a specific problem with clear context and impact
          required: true

  - type: textarea
    id: roo-code-tasks
    attributes:
      label: Roo Code Task Links (optional)
      description: If you explored this with Roo Code, share public task links for context.
      placeholder: Paste your Roo Code share links here, one per line

  - type: markdown
    attributes:
      value: |
        ---
        Optional (for contributors): You can stop here if you're just proposing the improvement.

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria (optional)
      description: Define what “working” looks like with specific, testable outcomes.
      placeholder: |
        Given [context]
        When [user action]
        Then [expected result]
        And [additional expectations]
        But [what should NOT happen]

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed approach (optional)
      description: If you have an idea, describe it briefly in plain language.

  - type: textarea
    id: risks
    attributes:
      label: Trade-offs / risks (optional)
      description: Potential downsides or alternatives considered.
